id: A14A0A11D
title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the Heart-Essence
  of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.322623
  last_modified_at: 2022-03-01 04:27:10.322626
