id: A14A0A11D
title: The Essential Activity Manual for the Awesome Ones’ Assembly, the Heart Practice
  of Vidyādharas, from the Heart Essence of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.270945
  last_modified_at: 2022-03-01 04:27:10.270947
