id: A14A0A11D
title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
  of India'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.189992
  last_modified_at: 2022-03-01 04:27:10.189997
