id: A14A0A11D
title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.318774
  last_modified_at: 2022-03-01 04:27:10.318777
