id: A14A0A11D
title: Confession and Fulfilment Insert for Accumulating the Practice of Turning Back
  the Summons of the Ḍākinīs
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.231442
  last_modified_at: 2022-03-01 04:27:10.231444
