id: A14A0A11D
title: 'The Refined Essence of Compassion: A Daily SÄdhana for the Natural Liberation
  of Suffering, the Secret Practice of the Great Compassionate One'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.283998
  last_modified_at: 2022-03-01 04:27:10.284001
