id: A14A0A11D
title: Yumka Fulfilment Practice
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.331603
  last_modified_at: 2022-03-01 04:27:10.331606
