id: A14A0A11D
title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.293684
  last_modified_at: 2022-03-01 04:27:10.293686
