id: A14A0A11D
title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great Perfection’s
  Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.268879
  last_modified_at: 2022-03-01 04:27:10.268882
