id: A14A0A11D
title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
  of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.316403
  last_modified_at: 2022-03-01 04:27:10.316406
