id: A14A0A11D
title: 'Words of the Vajra Queen: An Essential Daily Practice of the Vidyādharas’
  Female Practice'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.329436
  last_modified_at: 2022-03-01 04:27:10.329438
