id: A14A0A11D
title: Training in the Pure Realms of the Three KÄyas
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.325934
  last_modified_at: 2022-03-01 04:27:10.325937
