id: A14A0A11D
title: 'Rain of Accomplishments: A Concise Fulfilment Practice for the Female Awareness-Holder
  (Yumka)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.245955
  last_modified_at: 2022-03-01 04:27:10.245958
