id: A14A0A11D
title: Guru Yoga of Rigdzin Jigme Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.238485
  last_modified_at: 2022-03-01 04:27:10.238488
