id: A14A0A11D
title: Descent of Blessings of the Eight Vidyādharas
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.233965
  last_modified_at: 2022-03-01 04:27:10.233967
