id: A14A0A11D
title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.305910
  last_modified_at: 2022-03-01 04:27:10.305913
