id: A14A0A11D
title: 'A Glimpse of the Crucial Points: The VidyÄdhara''s Manual of Concealed Instructions'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.191630
  last_modified_at: 2022-03-01 04:27:10.191635
