id: A14A0A11D
title: Sādhana of the Great Master Vairotsana
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.262791
  last_modified_at: 2022-03-01 04:27:10.262793
