id: A14A0A11D
title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
  Practice of the Ḍākinī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.240244
  last_modified_at: 2022-03-01 04:27:10.240246
