id: A14A0A11D
title: A Prayer of Devotion, to Make the Tears Fall
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.203472
  last_modified_at: 2022-03-01 04:27:10.203474
