id: A14A0A11D
title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.199070
  last_modified_at: 2022-03-01 04:27:10.199072
