id: A14A0A11D
title: 'Rain of Siddhis: A Prayer to the Lineage of Rigdzin Düpa'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.248700
  last_modified_at: 2022-03-01 04:27:10.248703
