id: A14A0A11D
title: The Spontaneous Vajra Song of Fulfilment and Confession
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.303751
  last_modified_at: 2022-03-01 04:27:10.303755
