id: A14A0A11D
title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
  (Yumka)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:27:10.289376
  last_modified_at: 2022-03-01 04:27:10.289379
